services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend-container
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    container_name: backend-container
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hrm
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "28017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db
    restart: always

networks:
  app-network:

volumes:
  mongodb-data:
