version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend-container
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/hrm
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
